In [1]:
from zipfile import compressor_names

import numpy as np


In [2]:
A = np.array([
    [1, -5, 3],
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [3]:
print(A.shape)
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

(4, 3)
a_23= 1 a_32= 3 a_33= 1


In [4]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [5]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [6]:
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [7]:
Inc_after = 0.87 * Inc
Inc_after

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [8]:
P = Inc_after - Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [9]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [10]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [11]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [12]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [13]:
A@x

array([26, 30])

In [14]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [15]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [16]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [18]:
A=np.array([x,y,z])
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [19]:
import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7],
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0],
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
},
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5],
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4],
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2]
},
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [30]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [31]:
Com = Price_DF*com
Com

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               0.40             0.30         0.30     0.08  0.10
Борис             0.36             0.50         0.30     0.10  0.10
Вика              0.40             0.40         0.00     0.05  0.20
Галя              0.36             0.24         0.84     0.08  0.20
Дима              0.50             0.70         0.60     0.10  0.15
Егор              1.00             1.00         0.90     0.20  0.25
Женя              0.22             0.20         0.45     0.05  0.17
Юра               0.90             0.80         0.75     0.10  0.20

In [34]:
SD = np.sum(Count_DF*Com, axis=1)
SD

Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64

In [35]:
Full = np.sum(Count_DF*Price_DF, axis=1)
Full

Аня       61.5
Борис     90.1
Вика      71.0
Галя      88.4
Дима     208.5
Егор     135.0
Женя      77.7
Юра      196.0
dtype: float64

In [36]:
ZP = Full-SD
ZP

Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64

In [37]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [38]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [39]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 2

2


In [40]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 3

3
