In [1]:
import numpy as np
from sympy import *

In [6]:
a,b = symbols('a, b')
f = (5 - a - 2*b)**2
fda = f.diff(a)
fdb = f.diff(b)
np.array([fda, fdb])

array([2*a + 4*b - 10, 4*a + 8*b - 20], dtype=object)

In [7]:
M = {a:1, b:1}
np.array([fda.subs(M), fdb.subs(M)])

array([-4, -8], dtype=object)

In [8]:
solve([fda, fdb], a, b)

{a: 5 - 2*b}

In [9]:
w0, w1 = symbols('w0, w1')
f = (2.1 - w0 - w1)**2 + (2.9 - w0 - 3*w1)**2 + (4.1 - w0 - 5*w1)**2
fdw0 = f.diff(w0)
fdw1 = f.diff(w1)
print(fdw0, fdw1)
solve([fdw0, fdw1], w0, w1)

6.0*w0 + 18.0*w1 - 18.2 18.0*w0 + 70.0*w1 - 62.6


{w0: 1.53333333333333, w1: 0.500000000000000}

In [11]:
f = np.array([8, 2, 8, 3, 5, 6, 5, 15])
fg = np.gradient(f, 7)
fg[7]

1.4285714285714286

In [12]:
x, y, z = symbols('x, y, z')
f = 2*x**2 - 4*x*z + 4*y**2 - 8*y*z + 9*z**2 + 4*x + 8*y - 20*z
fdx = f.diff(x)
fdy = f.diff(y)
fdz = f.diff(z)
print(fdx, fdy, fdz)

4*x - 4*z + 4 8*y - 8*z + 8 -4*x - 8*y + 18*z - 20


In [17]:
curr = {x:0, y:0, z:0}
curr_p = np.array([0,0,0])
alpha = 0.25
curr_grad = np.array([fdx.subs(curr), fdy.subs(curr), fdz.subs(curr)])
curr_grad

array([4, 8, -20], dtype=object)

In [19]:
new_point = curr_p - alpha * curr_grad
new_point

array([-1.00000000000000, -2.00000000000000, 5.00000000000000],
      dtype=object)