In [138]:
import numpy as np
from sympy import *  # импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области значения
from sympy.calculus.util import continuous_domain #импортируем функцию для поиска области определения
from sympy.codegen.ast import float64

x = Symbol("x") #определяем нашу переменную
f = 1/x #определяем нашу функцию
continuous_domain(f, x, S.Reals) #вычисляем область определения

Union(Interval.open(-oo, 0), Interval.open(0, oo))

In [57]:
from sympy import log
x = Symbol("x")
f = log(x)/x
continuous_domain(f, x, S.Reals)

Interval.open(0, oo)

In [58]:
from sympy import Symbol, S, sin #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области значений
x = Symbol("x")
f = sin(x)
function_range(f, x, S.Reals)

Interval(-1, 1)

In [59]:
from sympy import Symbol, S #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области значений
from sympy import exp #добавляем функцию для вычисления экспоненциальной функции
x = Symbol("x")
f = (x*x-3)/(exp(x))
function_range(f, x, S.Reals)

Interval(-2*E, oo)

In [60]:
x = Symbol("x")
f = x*x+5*x+4
f.subs(x, 0)

4

In [61]:
from sympy import solveset, Eq
solveset(Eq(x*x+5*x+4, 0), x)

{-4, -1}

In [62]:
solveset(Eq(x*x+2*x-8, 0), x)

{-4, 2}

In [63]:
x = Symbol("x")
f = 3 / (x*x-10)
function_range(f, x, S.Reals)

Union(Interval(-oo, -3/10), Interval.open(0, oo))

In [64]:
24/15

1.6

In [65]:
import sympy
x = sympy.Symbol("x")
expr = x**4 + 3*x**3 + 4*x**2 + 8
expr.diff(x)

4*x**3 + 9*x**2 + 8*x

In [66]:
from sympy import diff, sin, exp, log, Symbol
x = sympy.Symbol("x")
expr = log(x**2 + 5*x) + exp(sin(x))
expr.diff(x)

(2*x + 5)/(x**2 + 5*x) + exp(sin(x))*cos(x)

In [67]:
x = sympy.Symbol("x")
expr = sin(x*3 + log(x))*exp((x))
expr.diff(x)

(3 + 1/x)*exp(x)*cos(3*x + log(x)) + exp(x)*sin(3*x + log(x))

In [68]:
x = sympy.Symbol("x")
expr = log(x**2 + 5*x) + exp(sin(x))
expr.diff(x,2)

-exp(sin(x))*sin(x) + exp(sin(x))*cos(x)**2 + 2/(x*(x + 5)) - (2*x + 5)**2/(x**2*(x + 5)**2)

In [69]:
expr = x / x**2 + 1
expr.diff(x,2)

2/x**3

In [70]:
from sympy import Symbol, S
from sympy.calculus.util import continuous_domain
x = Symbol("x")
f = (x**3)/(x**2-1)
continuous_domain(f, x, S.Reals)

Union(Interval.open(-oo, -1), Interval.open(-1, 1), Interval.open(1, oo))

In [71]:
from sympy import Symbol, S
from sympy.calculus.util import function_range
x = Symbol("x")
f = (x**3)/(x**2-1)
function_range(f, x, S.Reals)

Interval(-oo, oo)

In [72]:
from sympy import solveset, Eq
f = (x**3)/(x**2-1)
solveset(Eq(f, 0), x)

{0}

In [73]:
x = Symbol("x")
f = (x**3)/(x**2-1)
f.subs(x, 0)

0

In [74]:
import sympy
from sympy import diff
x = sympy.Symbol("x")
expr = (x**3)/(x**2-1)
expr.diff(x)

-2*x**4/(x**2 - 1)**2 + 3*x**2/(x**2 - 1)

In [75]:
y = expr.diff(x)
solveset(Eq(y, 0), x)

{0, -sqrt(3), sqrt(3)}

In [76]:
import sympy
from sympy import diff
x = sympy.Symbol("x")
expr = (x**3)/(x**2-1)
expr.diff(x,2)

2*x*(x**2*(4*x**2/(x**2 - 1) - 1)/(x**2 - 1) - 6*x**2/(x**2 - 1) + 3)/(x**2 - 1)

In [77]:
from sympy import Symbol, limit, oo
x = Symbol("x")
f = (x**3)/(x**2-1)
limit(f,x,oo)

oo

In [78]:
from sympy import Symbol, limit, oo
x = Symbol("x")
f = (x**3)/(x**2-1)
limit(f,x,1)

oo

In [79]:
from sympy import Symbol, limit, oo
x = Symbol("x")
f = (x**3)/(x**2-1)
limit(f,x,-1)

oo

In [80]:
from sympy import Symbol, limit, oo
x = Symbol("x")
f = (x**3)/((x**2-1)*x)
limit(f,x,oo)

1

In [81]:
from sympy import Symbol, limit, oo
x = Symbol("x")
f = (x**3)/((x**2-1)) - 1*x
limit(f,x,oo)

0

# Задание 8

In [82]:
x = Symbol("x")
f = (x**3)/(2*((x+5)**2))
continuous_domain(f, x, S.Reals)

Union(Interval.open(-oo, -5), Interval.open(-5, oo))

In [83]:
function_range(f, x, S.Reals)

Interval(-oo, oo)

In [84]:
solveset(Eq(f, 0), x)

{0}

In [85]:
f.subs(x, 0)

0

In [86]:
fd = f.diff(x)
fd

-x**3/(x + 5)**3 + 3*x**2/(2*(x + 5)**2)

In [87]:
solveset(Eq(fd, 0), x)

{-15, 0}

In [88]:
fd.subs(x, -20)

8/27

In [89]:
fd.subs(x, -10)

-2

In [90]:
fd.subs(x, -0.5)

0.0198902606310014

In [91]:
fd.subs(x, 2)

34/343

In [92]:
fdd = fd.diff(x)
fdd

3*x**3/(x + 5)**4 - 6*x**2/(x + 5)**3 + 3*x/(x + 5)**2

In [93]:
solveset(Eq(fdd, 0), x)

{0}

In [94]:
fdd.subs(x, -10)

-6/5

In [95]:
fdd.subs(x, -2)

-50/27

In [96]:
fdd.subs(x, 2)

150/2401

In [97]:
f = -x**3 + 3*(x**2)+9
continuous_domain(f, x, S.Reals)

Reals

In [98]:
fd = f.diff(x)
fd

-3*x**2 + 6*x

In [99]:
solveset(Eq(fd, 0), x)

{0, 2}

In [100]:
fd.subs(x, -1)

-9

In [101]:
fd.subs(x, 1)

3

In [102]:
fd.subs(x, 3)

-9

In [103]:
f = log(x) + x**3
f.diff(x)

3*x**2 + 1/x

In [104]:
f = -((x**2 + 1) / x)
fd = f.diff(x)
fd

-2 + (x**2 + 1)/x**2

In [105]:
solveset(Eq(fd, 0), x)

{-1, 1}

In [106]:
fd.subs(x, -2)

-3/4

In [107]:
fd.subs(x, -0.5)

3.00000000000000

In [108]:
fd.subs(x, 0.5)

3.00000000000000

In [109]:
fd.subs(x, 2)

-3/4

Для функции $f(x, y) = e^x + 5y^3x$ найдём частные производные первого и второго порядка:

$f_x' = e^x + 5yx^2$,
$f_{xx}'' = 5yx^2$.

$f_y' = 15y^2x$,
$f_{yy}'' = 30y$.

Таким образом, матрица Гессе будет иметь вид:

$$
H = \begin{bmatrix}
5yx^2 & 15y^2x \
15y^2x & 30y
\end{bmatrix}.
$$

In [111]:
x,y = symbols('x, y')
f = exp(x) + 5 * y**3 * x
fdx = f.diff(x)
fdy = f.diff(y)
fdxx = fdx.diff(x)
fdxy = fdx.diff(y)
fdyx = fdy.diff(x)
fdyy = fdy.diff(y)
print(fdxx, fdxy, fdyx, fdyy)

exp(x) 15*y**2 15*y**2 30*x*y


In [114]:
x,y = symbols('x, y')
f = -1 * x**2 + 6*x - 2*y**2 + 4*y
fdx = f.diff(x)
fdy = f.diff(y)
fdxx = fdx.diff(x)
fdxy = fdx.diff(y)
fdyx = fdy.diff(x)
fdyy = fdy.diff(y)
print(f'fdx = {fdx}')
print(f'fdy = {fdy}')
print(f'fdxx = {fdxx}')
print(f'fdxy = {fdxy}')
print(f'fdyx = {fdyx}')
print(f'fdyy = {fdyy}')

fdx = 6 - 2*x
fdy = 4 - 4*y
fdxx = -2
fdxy = 0
fdyx = 0
fdyy = -4


In [115]:
solveset(Eq(fdx, 0), x)

{3}

In [116]:
solveset(Eq(fdy, 0), y)

{1}

In [131]:
Hesse = np.array([[float(fdxx), float(fdxy)],[float(fdyx), float(fdyy)]])
Hesse

array([[-2.,  0.],
       [ 0., -4.]])

In [133]:
np.linalg.eig(Hesse)


EigResult(eigenvalues=array([-2., -4.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))

In [144]:
x,y = symbols('x, y')
f = x**3 + 3*x*y**2 - 15*x - 12*y + 1 
fdx = f.diff(x)
fdy = f.diff(y)
fdxx = fdx.diff(x)
fdxy = fdx.diff(y)
fdyy = fdy.diff(y)
print(f'fdx = {fdx}')
print(f'fdy = {fdy}')
print(f'fdxx = {fdxx}')
print(f'fdxy = {fdxy}')
print(f'fdyy = {fdyy}')

fdx = 3*x**2 + 3*y**2 - 15
fdy = 6*x*y - 12
fdxx = 6*x
fdxy = 6*y
fdyy = 6*x


In [140]:
extr = solve([Eq(fdx, 0), Eq(fdy, 0)], [x,y])
extr

[(-2, -1), (-1, -2), (1, 2), (2, 1)]

In [145]:
Hesse = np.array([[fdxx, fdxy],[fdxy, fdyy]])
Hesse

array([[6*x, 6*y],
       [6*y, 6*x]], dtype=object)

In [148]:
for point in extr:
    H = fdxx.subs(x, point[0]) * fdyy.subs(x, point[0]) - fdxy.subs(y, point[1])**2
    if H > 0 and fdxx.subs(x, point[0]) > 0:
        print("Минимум в точке", point)
    elif H > 0 and fdxx.subs(x, point[0]) < 0:
        print("Максимум в точке", point)
    elif H < 0:
        print("Седловая точка в точке", point)
    else:
        print("Точка", point, "не является точкой экстремума")


Максимум в точке (-2, -1)
Седловая точка в точке (-1, -2)
Седловая точка в точке (1, 2)
Минимум в точке (2, 1)


In [150]:
x,y = symbols('x, y')
f = 4*x**2 - 6*x*y - 34*x + 5*y**2 + 42*y + 7
fdx = f.diff(x)
fdy = f.diff(y)
print(f'fdx = {fdx}')
print(f'fdy = {fdy}')

fdx = 8*x - 6*y - 34
fdy = -6*x + 10*y + 42


In [151]:
solve([Eq(fdx, 0), Eq(fdy, 0)], [x,y])

{x: 2, y: -3}

In [152]:
x,y = symbols('x, y')
f = x**3 - 2*x*y - y**6
fdx = f.diff(x)
fdy = f.diff(y)
fdxx = fdx.diff(x)
fdxy = fdx.diff(y)
fdyy = fdy.diff(y)
Hesse = np.array([[fdxx, fdxy],[fdxy, fdyy]])
Hesse

array([[6*x, -2],
       [-2, -30*y**4]], dtype=object)

In [153]:
fdxx.subs(x, 1) * fdyy.subs(y, 2) - fdxy**2

-2884

In [155]:
x,y = symbols('x, y')
f = x**3 + y**3 - 3*x*y
fdx = f.diff(x)
fdy = f.diff(y)
fdxx = fdx.diff(x)
fdxy = fdx.diff(y)
fdyy = fdy.diff(y)
print(f'fdx = {fdx}')
print(f'fdy = {fdy}')
print(f'fdxx = {fdxx}')
print(f'fdxy = {fdxy}')
print(f'fdyy = {fdyy}')
extr = solve([Eq(fdx, 0), Eq(fdy, 0)], [x,y])
print(f'Экстремумы - {extr}')


fdx = 3*x**2 - 3*y
fdy = -3*x + 3*y**2
fdxx = 6*x
fdxy = -3
fdyy = 6*y
Экстремумы - [(0, 0), (1, 1), ((-1/2 - sqrt(3)*I/2)**2, -1/2 - sqrt(3)*I/2), ((-1/2 + sqrt(3)*I/2)**2, -1/2 + sqrt(3)*I/2)]


In [156]:
for point in extr:
    H = fdxx.subs(x, point[0]) * fdyy.subs(y, point[1]) - fdxy**2
    if H > 0 and fdxx.subs(x, point[0]) > 0:
        print("Минимум в точке", point)
    elif H > 0 and fdxx.subs(x, point[0]) < 0:
        print("Максимум в точке", point)
    elif H < 0:
        print("Седловая точка в точке", point)
    else:
        print("Точка", point, "не является точкой экстремума")

Седловая точка в точке (0, 0)
Минимум в точке (1, 1)


TypeError: Invalid comparison of non-real 6*(-1/2 - sqrt(3)*I/2)**2