In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [3]:
s[2]

50

In [4]:
len(s)

4

In [7]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
display(a + b)
## array([15, 23, 14,  8])
a - b
## array([ 5, -7, -4, -6])

array([15, 23, 14,  8])

array([ 5, -7, -4, -6])

In [8]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

Доходы мужа: 120, 150 и 190 тысяч рублей.
Доходы жены: 130, 130 и 130 тысяч рублей.
Доходы тёщи: 2, 3 и 2.5 тысячи евро.

In [9]:
m = np.array([120, 150, 190])
z = np.array([130, 130, 130])
te = np.array([2, 3, 2.5])
t = te * 72
display(t)

array([144., 216., 180.])

In [10]:
display(m + z + t)

array([394., 496., 500.])

In [11]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

In [12]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])
om1 = 2
om2 = -3
om3 = 5

display(om1 * x + om2 * y + om3 * u)


array([7, 7])

In [13]:
q = np.array([3,4,5,9])
s = np.array([1,5,3,6])
ss = 200
p = 400
display(p * s - ss * q)

array([-200, 1200,  200,  600])

In [14]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

In [15]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85],
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65],
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5],
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10],
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [19]:
display(Hut_Paradise_DF.values[4])

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [20]:
Hut_Paradise_DF.values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [21]:
Hut_Paradise_DF.values[:, 1] - Hut_Paradise_DF.values[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [22]:
Hut_Paradise_DF['2.Area'].values - Hut_Paradise_DF['6.Liv.Area'].values

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [23]:
(Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']).values

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [24]:
pr = np.array([10,20,30,15,5,40,20,8,20])
Hut_Paradise_DF['5.Demo two weeks'].values@pr

1348

In [25]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [27]:
comb = 2*v + (-3)*w
comb

array([-3, 14,  3,  4,  2])

In [28]:
comb@u

0