In [1]:
import numpy as np

In [2]:
A = np.array([[1,1], [1,2]])
A

array([[1, 1],
       [1, 2]])

In [3]:
A.T@A

array([[2, 3],
       [3, 5]])

In [4]:
A = np.array([[1,2], [3,7]])
A

array([[1, 2],
       [3, 7]])

In [5]:
np.linalg.inv(A)

array([[ 7., -2.],
       [-3.,  1.]])

In [6]:
v1 = np.array([2,10,-2])
v2 = np.array([3,2,-2])
v3 = np.array([8,14,-6])
M = np.array([v1,v2,v3]).T
M

array([[ 2,  3,  8],
       [10,  2, 14],
       [-2, -2, -6]])

In [7]:
np.linalg.matrix_rank(M)

2

In [8]:
A = np.array([[5,10], [1,2]])
A

array([[ 5, 10],
       [ 1,  2]])

In [9]:
np.linalg.matrix_rank(A)

1